# Sceptre configuration file
region: ap-northeast-1

# Settings for stack groups
project_code: poc
environment: poc

# Specify the S3 bucket name to store CloudFormation template files
# If the template file size is up to 50Kbyte, you do not need to specify
# If it exceeds 50Kbyte, specify an S3 bucket
# If the specified S3 bucket does not exist, Sceptre will automatically create it
#template_bucket_name: cf-templates-example

# You can also specify the profile to use when running Sceptre
# When running in CloudShell, the role you logged in with will be used
# profile: rcloud-migration-prod
# profile: xadmin-stg-admin

# Default tags applied to all resources
tags:
  Environment: poc
  Project: POC
  Owner: DevOps
  Purpose: ProofOfConcept

# Tags to be attached to resources generated in the stack group
stack_tags:
  Env: poc
